version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # 👈 Volumen persistente añadido
    networks:
      - redesd

  scraper:
    build:
      context: ./scraper
    container_name: scraper
    volumes:
      - ./scraper:/app
    depends_on:
      - mongo
    networks:
      - redesd

networks:
  redesd:
    driver: bridge

volumes:
  mongodb_data:  



