version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      redesd: {}  # Formato correcto para networks

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru
    networks:
      redesd: {}

  scraper:
    build:
      context: ./scraper
    container_name: scraper
    volumes:
      - ./scraper:/app
    depends_on:
      - mongo
    networks:
      redesd: {}

  cache:
    build:
      context: ./cache
    container_name: cache
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    networks:
      redesd: {}

  generador_trafico:
    build:
      context: ./generador_trafico
    container_name: generador_trafico
    depends_on:
      - cache
    networks:
      redesd: {}

  pig:
    build:
      context: ./docker-pig
    container_name: pig
    volumes:
      - ./docker-pig:/app
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      redesd: {}

networks:
  redesd:
    driver: bridge

volumes:
  mongodb_data:
    name: mongodb_data  # Definición explícita del volumen





