version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - redesd

  scraper:
    build:
      context: ./scraper   
    volumes:
      - ./scraper:/app     
    depends_on:
      - mongo
    networks:
      - redesd

networks:
  redesd:
    driver: bridge



