version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - redesd

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-fifo
    networks:
      - redesd

  scraper:
    build:
      context: ./scraper
    container_name: scraper
    volumes:
      - ./scraper:/app
    depends_on:
      - mongo
    networks:
      - redesd

  cache:
    build: ./cache
    container_name: cache
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    networks:
      - redesd

  generador_trafico:
    build: ./generador_trafico
    container_name: generador_trafico
    depends_on:
      - cache
    networks:
      - redesd

networks:
  redesd:
    driver: bridge

volumes:
  mongodb_data:





